Redesign 1
svvsaga/docs-public pull request #13
Opened 2022-05-20 10:59 UTC by PrebenAas

Created new landing page for documentation. Works in both light and dark mode.

![image](https://user-images.githubusercontent.com/20104610/169514144-5cc6d624-b134-4273-83a8-53e5c231b393.png)

![image](https://user-images.githubusercontent.com/20104610/169514267-d2e906f6-c229-432b-b826-5cb5192ed7f4.png)

2022-05-23 07:49 UTC, torgeir requested changes
Ser bra ut! Noen innspill

2022-05-23 07:49 UTC, torgeir commented on src/css/custom.css
> +  padding: 2 0 2 0;
Andre verdier enn 0 må ha enhet

2022-05-23 07:49 UTC, torgeir commented on src/css/custom.css
> +@media (max-width: 800px){
Jeg syns ofte media-queries er enklere å tenke på om man lar "mobilskjerm" være default, og heller styler basert på min-width. Da trenger du bare én mediaquery for å treffe "store skjermer"

2022-05-23 07:49 UTC, torgeir commented on src/css/custom.css
> +    margin-left: -3.8rem;
Er det fordi tegninga ikke starter ytterst i canvasen, kanskje det er noe der vi kan tune heller?

2022-05-23 07:49 UTC, torgeir commented on src/css/custom.css
> +}
Den tror jeg du kan slippe ved å bruke noen av stylesene som følger med, åpne developer tools og styles.css og ta en titt på de som fins fra før av. Der mener jeg å ha sett feks .margin-top--lg og lignende

2022-05-23 07:49 UTC, torgeir commented on src/components/HomepageFeatures/animation.tsx
> +  return <canvas className={"animation"} ref={canvasRef} width="600" height="600" style={{}} />
For strings trengs ikke objekter. Tom style har heller ingen effekt
```suggestion
  return <canvas className="animation" ref={canvasRef} width="600" height="600" />
```

2022-05-23 15:26 UTC, PrebenAas commented on src/css/custom.css
> +  padding: 2 0 2 0;
Done!

2022-05-23 15:51 UTC, PrebenAas commented on src/css/custom.css
> +@media (max-width: 800px){
Ja, ser den. Denne querien kommer inn for å fjerne animasjonen når skjermen blir for liten. Gjør det for å slippe skalering av animasjon som også ødela `width` av hele containeren og la til horisontal scroll. Forslag hvor jeg heller bør løse det? Legge alt inne i en `min-width`?

2022-05-24 07:39 UTC, torgeir commented on src/components/HomepageFeatures/animation.tsx
> +  console.log(canvas.width, canvas.height)
```suggestion
```

2022-05-24 07:40 UTC, torgeir commented on src/css/custom.css
> +@media (max-width: 800px){
Da må du gjøre det omvent, la den være display: none per default og vise den igjen når min-width blir stor nok

2022-05-24 11:51 UTC, PrebenAas commented on src/css/custom.css
> +@media (max-width: 800px){
Vi fikser dette når vi evt. utvider kompleksiteten.

2022-05-24 11:52 UTC, torgeir commented on src/css/custom.css
> +@media (max-width: 800px){
Enig.

2022-05-24 12:01 UTC, merged