Clean up text due to user feedback + added figure
svvsaga/docs-public pull request #14
Opened 2022-06-02 13:04 UTC by PrebenAas

First iteration to clean up language and wording. Added visual aid to help the reader understand where we are and where we want.

2022-06-02 13:29 UTC, PrebenAas commented on docs/01-intro.md
> +De fleste datasettene på plattformen er tilgjengeliggjort i sin standardiserte form i [BigQuery](bigquery). Her kan du dra nytte av eksisterende SQL-kunnskap for å gjøre avanserte analyser på store m
Den linker bare til en annen side i docs! Skal funke fint. Notion-lenken var feil og heller ikke tilgjengelig for folk utenfor Saga.

2022-06-02 13:51 UTC, geirsagberg commented on docs/01-intro.md
> +De fleste datasettene på plattformen er tilgjengeliggjort i sin standardiserte form i [BigQuery](bigquery). Her kan du dra nytte av eksisterende SQL-kunnskap for å gjøre avanserte analyser på store m
Alright, da får vi prøve :)

2022-06-02 13:51 UTC, geirsagberg approved these changes

2022-06-03 06:31 UTC, torgeir requested changes

2022-06-03 06:31 UTC, torgeir commented on docs/01-intro.md
> +Med dataplattformen Saga ønsker vi å samle mest mulig relevant data og tilgjengeliggjøre disse på et standardisert og kompatibelt format. Dette skal gjøre det bedre å utføre analyser og sammenstillin
```suggestion
Med dataplattformen Saga ønsker vi å samle mest mulig relevant data og tilgjengeliggjøre disse på et standardisert og kompatibelt format. Dette gjør det enklere å utføre analyser og sammenstillinger uten å måtte bruke mye tid på oppsett, leting etter data og bestillinger.
```
Vi må tro på det! 😬

2022-06-03 06:35 UTC, torgeir commented on docs/01-intro.md
> +![Visualisering av hva Saga ønsker å oppnå med ny plattform](/img/saga-goal.png)
Må det ikke være `img/saga-goal.png` her tro, sånn at man ikke havner på svvsaga.github.io/img/saga-goal.png?

2022-06-03 06:40 UTC, PrebenAas commented on docs/01-intro.md
> +![Visualisering av hva Saga ønsker å oppnå med ny plattform](/img/saga-goal.png)
Det er nok helt riktig!

2022-06-03 07:09 UTC, torgeir approved these changes

2022-06-03 07:11 UTC, torgeir commented on docs/01-intro.md
> +![Visualisering av hva Saga ønsker å oppnå med ny plattform](/img/saga-goal.png)
Jeg tar det tilbake, virker som docusaurus gjør noe triks når man referer det som ligger ytterst i static.

2022-06-03 08:17 UTC, merged